[common]
server_addr=127.0.0.1:28024
conn_type=tcp
vkey=public-demo
auto_reconnection=true
crypt=false
compress=false
disconnect_timeout=20
tls_enable=false
remark=auth-e2e
ipwhite=1
ipwhitepass=secret pass
ipwhitelist=127.0.0.1

[web]
host=192.168.100.191
target_addr=127.0.0.1:28090
location=/
