appname = rustnps
runmode = dev
http_proxy_ip=0.0.0.0
http_proxy_port=28080
https_proxy_port=28443
https_just_proxy=false
bridge_type=tcp
bridge_ip=127.0.0.1
bridge_port=28024
public_vkey=public-demo
web_ip=127.0.0.1
web_port=28081
web_username=admin
web_password=123
allow_user_login=true
allow_user_register=false
open_captcha=false
allow_user_change_username=true
http_cache=false
http_cache_length=100
http_add_origin_header=true
disconnect_timeout=20
tls_enable=false
log_level=trace
log_path=
