[common]
server_addr=127.0.0.1:19024
conn_type=tcp
vkey=compress-key
auto_reconnection=true
max_conn=32
flow_limit=0
rate_limit=0
crypt=false
compress=true
disconnect_timeout=60
tls_enable=false

[file]
mode=tcp
target_addr=127.0.0.1:28081
server_port=20081
