[common]
server_addr=127.0.0.1:19024
conn_type=tcp
vkey=flow-key
auto_reconnection=true
max_conn=32
flow_limit=1
rate_limit=0
crypt=false
compress=false
disconnect_timeout=60
tls_enable=false

[file]
mode=tcp
target_addr=127.0.0.1:28081
server_port=20083
