appname = rustnps
runmode = dev

http_proxy_ip=127.0.0.1
http_proxy_port=19080
https_proxy_port=19443
https_just_proxy=false

bridge_type=tcp
bridge_ip=127.0.0.1
bridge_port=19024
public_vkey=123

web_ip=127.0.0.1
web_port=19081
web_username=admin
web_password=123
allow_user_login=true
allow_user_register=false
allow_user_change_username=true

allow_flow_limit=true
allow_rate_limit=true
allow_tunnel_num_limit=true
allow_connection_num_limit=true
allow_local_proxy=true
allow_multi_ip=true
http_cache=false
http_cache_length=100
http_add_origin_header=true
ip_limit=false
disconnect_timeout=60
tls_enable=false
log_level=7
log_path=
